### ISSUE TITLE
The date for carbon is not working on php 5.3 +

### ISSUE THREAD

**Issue by Hujjat** [PHLAK/laravelcollective-html-form-snippets#1]
Hi, 

Thanks for your great package. There is a small issue with ` formdate`
When we use it, It autocompletes the following code. 
`{!! Form::date($name, \Carbon\Carbon\::now(), []) !!}`

It causes an error for that last slash ( \ ). it should be without slash, like this. 
`{!! Form::date($name, \Carbon\Carbon::now(), []) !!}`

thanks :)

**Comment by PHLAK** [comment]
Thanks @Hujjat, it appears I made a typo.

**Comment by PHLAK** [comment]
Resolved with commit 82148c5
